import type { Character } from '../types';

export const CHARACTERS: Character[] = [
  // 4 GIRLS
  {
    id: 'girl-1',
    name: 'Leyla',
    gender: 'girl',
    skinTone: '#FDDBB4',
    hairColor: '#4A2B0A',
    hairStyle: 'long-wavy',
    outfitColor: '#ec4899',
    outfitAccent: '#f472b6',
    eyeColor: '#4B3F2F',
    hasGlasses: false,
    hasHijab: false,
    thumbnail: '/assets/portraits/girl_leyla.jpg',
  },
  {
    id: 'girl-2',
    name: 'Amara',
    gender: 'girl',
    skinTone: '#8D5524',
    hairColor: '#1A0A00',
    hairStyle: 'curly-puffs',
    outfitColor: '#FCD34D',
    outfitAccent: '#F97316',
    eyeColor: '#2D1B00',
    hasGlasses: false,
    hasHijab: false,
    thumbnail: '/assets/portraits/girl_amara.jpg',
  },
  {
    id: 'girl-3',
    name: 'Mei',
    gender: 'girl',
    skinTone: '#FDDBB4',
    hairColor: '#1A1A1A',
    hairStyle: 'double-buns',
    outfitColor: '#EF4444',
    outfitAccent: '#F59E0B',
    eyeColor: '#1A1A1A',
    hasGlasses: false,
    hasHijab: false,
    thumbnail: '/assets/portraits/girl_mei.jpg',
  },
  {
    id: 'girl-4',
    name: 'Zara',
    gender: 'girl',
    skinTone: '#FDDBB4',
    hairColor: '#2C1A0E',
    hairStyle: 'hijab',
    outfitColor: '#A855F7',
    outfitAccent: '#C084FC',
    eyeColor: '#2D3748',
    hasGlasses: false,
    hasHijab: true,
    thumbnail: '/assets/portraits/girl_zara.jpg',
  },

  // 4 BOYS
  {
    id: 'boy-1',
    name: 'Tom',
    gender: 'boy',
    skinTone: '#A66A44',
    hairColor: '#1A1A1A',
    hairStyle: 'short-curly',
    outfitColor: '#2563EB',
    outfitAccent: '#3B82F6',
    eyeColor: '#4A3728',
    hasGlasses: false,
    hasHijab: false,
    thumbnail: '/assets/portraits/boy_tom.jpg',
  },
  {
    id: 'boy-2',
    name: 'Leo',
    gender: 'boy',
    skinTone: '#FDDBB4',
    hairColor: '#4A2B0A',
    hairStyle: 'short-wavy',
    outfitColor: '#16A34A',
    outfitAccent: '#22C55E',
    eyeColor: '#3B2F2F',
    hasGlasses: true,
    hasHijab: false,
    thumbnail: '/assets/portraits/boy_leo.jpg',
  },
  {
    id: 'boy-3',
    name: 'Ali',
    gender: 'boy',
    skinTone: '#D99B65',
    hairColor: '#1A1A1A',
    hairStyle: 'short-spiky',
    outfitColor: '#E11D48',
    outfitAccent: '#FB7185',
    eyeColor: '#2A1F1D',
    hasGlasses: false,
    hasHijab: false,
    thumbnail: '/assets/portraits/boy_ali.jpg',
  },
  {
    id: 'boy-4',
    name: 'Murad',
    gender: 'boy',
    skinTone: '#E8B88A',
    hairColor: '#382212',
    hairStyle: 'side-part',
    outfitColor: '#EAB308',
    outfitAccent: '#1E3A8A',
    eyeColor: '#3A2E2B',
    hasGlasses: false,
    hasHijab: false,
    thumbnail: '/assets/portraits/boy_murad.jpg',
  },
];

export const DEFAULT_CHARACTER_ID = 'girl-1';
